### ISSUE TITLE
doctrine:migrations:diff not working with dbal 4.0 when using multiple schemas.

### ISSUE THREAD

**Issue by jochen-jung** [doctrine/migrations#1460]
### Bug Report

Platform: MySQL 8.0
doctrine/doctrine-bundle 2.13.0
doctrine/dbal 4.1.1

Since we upgraded to doctrine/dbal 4.0 "bin/console doctrine:migrations:diff --em=schema_name" does re-create all database tables.

The issue seems to be the schema_name. As there are all tables being created with the schema name and dropped again without the schema name:

Up-Migration:
CREATE TABLE schema_name.table_name
DROP TABLE table_name

Down-Migration:
CREATE TABLE table_name
DROP TABLE schema_name.table_name

I would expect it to show only new fields in a table. And not drop and create each table.

Note: When I remove schema from the attribute in the entity, it is working. But then of course without the schema prefixed in the up and down migration code.
#[ORM\Table(name: 'table_name', schema: 'schema_name')]

**Comment by pschombara** [comment]
Additional information:

`\Doctrine\DBAL\Schema\MySQLSchemaManager` does not implement `\Doctrine\DBAL\Schema\AbstractSchemaManager::listSchemaNames` and `\Doctrine\DBAL\Platforms\AbstractPlatform::supportsSchemas`.
Out of this reason the fourth parameter of the `\Doctrine\DBAL\Schema\Schema::__construct` is an empty array.

The array keys of the `_tables` property looks like `.table_name` instead of `schema.table_name`.
When the changes are checked in `\Doctrine\DBAL\Schema\Comparator::compareSchemas` the method `\Doctrine\DBAL\Schema\Schema::hasTable` is used which compare `schema.table_name` with `.table_name` which is always false.
